name: Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Make repo lowercase'
            run: |
              echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
              
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GH_TOKEN}}

          - name: 'Docker Layer Caching'
            uses: jpribyl/action-docker-layer-caching@v0.1.1
            continue-on-error: true


          - name: 'Build & Publish Docker Image'
            run: |
              docker build . --tag "ghcr.io/${REPO}:latest"
              docker push "ghcr.io/${REPO}:latest"
